### ISSUE TITLE
Clarify usage of `Credentials` to load `Private-Token` (for private repositories)

### ISSUE THREAD

**Issue by oschrenk** [gilcloud/sbt-gitlab#17]
The documentation states that `credentials += Credentials(Path.userHome / ".sbt" / ".credentials.gitlab"),` can be used to load credentials for Gitlab. I believe this mechanism is not used by the plugin.

1. Only GitlabCredentials are being injected https://github.com/gilcloud/sbt-gitlab/blob/a6e8ceeacb755bd17c9b88724831c9371903a3ad/src/main/scala/com/gilcloud/sbt/gitlab/HeaderInjector.scala#L7
2. There is no usage of https://github.com/gilcloud/sbt-gitlab/blob/a6e8ceeacb755bd17c9b88724831c9371903a3ad/src/main/scala/com/gilcloud/sbt/gitlab/GitlabCredentials.scala#L14

When relying on the ivy credentials, I can't download my dependency. See also a comment https://github.com/gilcloud/sbt-gitlab/issues/12#issuecomment-727929635

---

I created a workaround by checking the for the `CI_JOB_TOKEN` environment variable and then load the credentials manually when it doesn't exist, meaning that I am on my local environment:

```
ThisBuild / useCoursier := false

import com.gilcloud.sbt.gitlab.{GitlabCredentials, GitlabPlugin}
GitlabPlugin.autoImport.gitlabDomain := "gitlab.acme.com"
GitlabPlugin.autoImport.gitlabCredentials := {
  sys.env.get("CI_JOB_TOKEN") match {
    // Gitlab CI pipeline
    case Some(t) =>
      Some(GitlabCredentials("Job-Token", t))
    // local machine
    case None =>
      val c = Credentials
        // realm=gitlab-maven
        // host=gitlab.acme.com
        // user=Private-Token
        // password=<TOKEN>
        .loadCredentials(Path.userHome / ".sbt" / ".credentials.gitlab")
        .left
        .map(s => new IllegalArgumentException(s))
        .toTry
        .get
      Some(GitlabCredentials(c))
  }
}

resolvers ++= Seq(
  "gitlab-maven" at "https://gitlab.acme.com/api/v4/projects/1337/packages/maven"
)

```

**Comment by listba** [comment]
@oschrenk What is the value for `realm` in you `credentials.gitlab` file. I see in your example above that have a commented out credentials file with `realm=gitlab-maven` The plugin is filtering the loaded credential files based on the realm and is looking explicitly for the first one that matches `realm=gitlab` and creating a `GitlabCredential` based off that

https://github.com/gilcloud/sbt-gitlab/blob/c9b060e8bc2a470f888ce7281f80df795fd5ffde/src/main/scala/com/gilcloud/sbt/gitlab/GitlabPlugin.scala#L90

I ran into a similar issue because I too had `realm=gitlab-maven` in mine so it was not getting matched by this filter.
Maybe the importance of the realm value should be called out in the README?

**Comment by oschrenk** [comment]
@listba  Thank you for pointing this out, and for pointing to the code. I missed that.

I did indeed use `gitlab-maven`. I think I followed the naming structure in the [Gitlab documentation](https://docs.gitlab.com/ee/user/packages/maven_repository/#authenticate-to-the-package-registry-with-maven) and got confused.

This indeed reduces the code to

```
import com.gilcloud.sbt.gitlab.GitlabPlugin
GitlabPlugin.autoImport.gitlabDomain := "gitlab.badgersystems.de"
// realm=gitlab
// host=gitlab.badgersystems.de
// user=Private-Token
// password=<API-KEY>
credentials += Credentials(Path.userHome / ".sbt" / ".credentials.gitlab")
resolvers ++= Seq(
  "gitlab-maven" at "https://gitlab.acme.com/api/v4/projects/1337/packages/maven"
)
```
